# Site setings
name: 'Javier Páramo'
description: ''
meta_description: ''
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: 
production_url: https://javierparamo.me/
disqus: 
mailchimp_url: ''
cover_image: bc_1.jpg
ga_analytics: UA-134158130-1


# Author
author:
  name: 'Javier Páramo'
  image: 'avatar.jpg'
  greetings: "Javier Páramo"
  description: "Architecture engineer, passionate urbanist, and "
  bio: ''

# Contact form setings
email: javier@javierparamo.me
contact_page_description: ""
thankyou_page_description: ""

# Social links
medium: 
instagram: 'jav_paramo'
twitter: 'jav_paramo'
facebook: 'luisjavier.ortegaparamo.3'
github: 
codepen: 
dribbble: 
pinterest: 
linkedin: 
producthunt: 

# Navigation
navigation:

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
