# Site setings
name: 'Javier Páramo'
description: ''
meta_description: ''
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: 
production_url: https://trankimtung.com/
disqus: 
mailchimp_url: ''
cover_image: bc_1.jpg
ga_analytics: UA-134158130-1


# Author
author:
  name: 'Tran Kim Tung'
  image: 'https://scontent-atl3-1.cdninstagram.com/vp/47b7b84c24c40f6497f8dd310b9c3ad6/5D1E6D65/t51.2885-19/39301484_2214133461961549_2025694498792669184_n.jpg?_nc_ht=scontent-atl3-1.cdninstagram.com'
  greetings: "Tran Kim Tung"
  description: "Architecture engineer, natural leader, "
  bio: ''

# Contact form setings
email: contact@trankimtung.com
contact_page_description: ""
thankyou_page_description: ""

# Social links
medium: '@trankimtung'
instagram: 'trankimtungxd'
twitter: 'trankimtungxd'
facebook: 
github: 'trankimtung'
codepen: 
dribbble: 
pinterest: 
linkedin: 
producthunt: 

# Navigation
navigation:

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
